# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 14) do

  create_table "comments", :force => true do |t|
    t.column "student_id",    :integer
    t.column "exercise_id",   :integer
    t.column "tech_grade_id", :integer
    t.column "comments",      :text
    t.column "user_id",       :integer, :limit => 10, :null => false
  end

  create_table "courses", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
  end

  create_table "deliverables", :force => true do |t|
    t.column "name",         :string
    t.column "description",  :text
    t.column "inactive_ind", :boolean
    t.column "exercise_id",  :integer
    t.column "type_id",      :integer
    t.column "sort_order",   :integer
  end

  create_table "exercises", :force => true do |t|
    t.column "name",         :string
    t.column "description",  :text
    t.column "inactive_ind", :boolean
    t.column "course_id",    :integer
    t.column "sort_order",   :integer
  end

  create_table "exercises_roles", :id => false, :force => true do |t|
    t.column "exercise_id", :integer, :default => 0, :null => false
    t.column "role_id",     :integer, :default => 0, :null => false
  end

  create_table "exercises_users", :id => false, :force => true do |t|
    t.column "exercise_id", :integer, :default => 0, :null => false
    t.column "user_id",     :integer, :default => 0, :null => false
  end

  create_table "results", :force => true do |t|
    t.column "student_id",     :integer
    t.column "deliverable_id", :integer
    t.column "user_id",        :integer
  end

  create_table "roles", :force => true do |t|
    t.column "name",         :string
    t.column "inactive_ind", :boolean
  end

  create_table "sections", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
  end

  create_table "setups", :force => true do |t|
    t.column "course_id",  :integer
    t.column "section_id", :integer
  end

  create_table "students", :force => true do |t|
    t.column "name",         :string
    t.column "section_id",   :integer
    t.column "inactive_ind", :boolean
  end

  create_table "types", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
    t.column "score_ind",   :boolean
    t.column "sort_order",  :integer
  end

  create_table "users", :force => true do |t|
    t.column "login",           :string
    t.column "hashed_password", :string
    t.column "email",           :string
    t.column "salt",            :string
    t.column "role_id",         :integer
    t.column "created_at",      :datetime
  end

end
